### ISSUE TITLE
[3.1.7] Internal Server Error - hasFreeShipping()

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/postie#137]
### Describe the bug

My client was getting an internal server error, I think we traced it back to this:
``
2024-08-01 11:46:34 [web.ERROR] [Error] Call to a member function hasFreeShipping() on null {"trace":["#0 /home/www/NEW/vendor/verbb/postie/src/helpers/PostieHelper.php(40): verbb\\postie\\helpers\\PostieHelper::getOrderLineItems()","#1 /home/www/NEW/vendor/verbb/postie/src/base/Provider.php(404): verbb\\postie\\helpers\\PostieHelper::getSignature()","#2 /home/www/NEW/vendor/verbb/postie/src/services/Service.php(144): verbb\\postie\\base\\Provider->getShippingRates()","#3 /home/www/NEW/vendor/verbb/postie/src/services/Service.php(182): verbb\\postie\\services\\Service->getShippingMethodsForOrder()","#4 [internal function]: verbb\\postie\\services\\Service->registerShippingMethods()","#5 /home/www/NEW/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()","#6 /home/www/NEW/vendor/yiisoft/yii2/base/Component.php(650): yii\\base\\Event::trigger()","#7 /home/www/NEW/vendor/craftcms/commerce/src/services/ShippingMethods.php(118): yii\\base\\Component->trigger()","#8 /home/www/NEW/vendor/craftcms/commerce/src/elements/Order.php(1990): craft\\commerce\\services\\ShippingMethods->getMatchingShippingMethods()","#9 /home/www/NEW/vendor/craftcms/commerce/src/elements/Order.php(1882): craft\\commerce\\elements\\Order->getAvailableShippingMethodOptions()","#10 /home/www/NEW/vendor/craftcms/commerce/src/elements/Order.php(2046): craft\\commerce\\elements\\Order->recalculate()","#11 /home/www/NEW/vendor/craftcms/cms/src/services/Elements.php(3443): craft\\commerce\\elements\\Order->afterSave()","#12 /home/www/NEW/vendor/craftcms/cms/src/services/Elements.php(1109): craft\\services\\Elements->_saveElementInternal()","#13 /home/www/NEW/vendor/craftcms/commerce/src/services/Carts.php(167): craft\\services\\Elements->saveElement()","#14 /home/www/NEW/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\\commerce\\services\\Carts->getCart()","#15 /home/www/NEW/vendor/craftcms/cms/src/helpers/Template.php(149): twig_get_attribute()","#16 /home/www/NEW/storage/runtime/compiled_templates/c1/c1e75b2f35badaa76cabfb9a9532423d.php(44): craft\\helpers\\Template::attribute()","#17 /home/www/NEW/vendor/twig/twig/src/Template.php(394): __TwigTemplate_6496d841108d6fe888a4cf368cb33dee->doDisplay()","#18 /home/www/NEW/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#19 /home/www/NEW/storage/runtime/compiled_templates/95/95f98e90cbe170b1d595f82135b2ae44.php(46): Twig\\Template->display()","#20 /home/www/NEW/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b5c5aed7579f2aa5a84555f52b53a941->doDisplay()","#21 /home/www/NEW/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#22 /home/www/NEW/vendor/twig/twig/src/Template.php(379): Twig\\Template->display()","#23 /home/www/NEW/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\\Template->render()","#24 /home/www/NEW/vendor/twig/twig/src/Environment.php(280): Twig\\TemplateWrapper->render()","#25 /home/www/NEW/vendor/craftcms/cms/src/web/View.php(488): Twig\\Environment->render()","#26 /home/www/NEW/vendor/craftcms/cms/src/web/View.php(541): craft\\web\\View->renderTemplate()","#27 /home/www/NEW/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\\web\\View->renderPageTemplate()","#28 /home/www/NEW/vendor/yiisoft/yii2/web/Response.php(1109): craft\\web\\TemplateResponseFormatter->format()","#29 /home/www/NEW/vendor/craftcms/cms/src/web/Response.php(338): yii\\web\\Response->prepare()","#30 /home/www/NEW/vendor/yiisoft/yii2/web/Response.php(340): craft\\web\\Response->prepare()","#31 /home/www/NEW/vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()","#32 /home/www/NEW/web/index.php(23): yii\\base\\Application->run()","#33 {main}"],"memory":6380032,"exception":"[object] (Error(code: 0): Call to a member function hasFreeShipping() on null at /home/www/NEW/vendor/verbb/postie/src/helpers/PostieHelper.php:117)"} 
``

I can't reproduce it myself. I just nuked the compiled caches but it seems to be related to hasFreeShipping()?

### Steps to reproduce

I believe this only happens when she was logged in, If I open a private browsing window it doesn't happen. She also mentioned when it uses Chrome it doesn't happen, only in Safari. 

Might be a cookie issue?

### Craft CMS version

 4.10.7

### Plugin version

3.1.7

### Additional context

Craft Commerce 4.6.3.1

**Comment by engram-design** [comment]
Looks like this is from:

https://github.com/verbb/postie/blob/ac46041ba4d758c64f048c4040c3572bd27fed76/src/helpers/PostieHelper.php#L117

Which is odd, as it's looking at a line item, but can't find the purchasable. I suppose maybe the variant has been deleted.

Should be fixed in [3.1.8](https://github.com/verbb/postie/releases/tag/3.1.8)

**Comment by RitterKnightCreative** [comment]
As always you rock -Thank you!
